### ISSUE TITLE
pp-picodet模型转化为paddle-lite模型用于安卓部署时，出现这个错误Error: This model is not supported, because kernel for 'calib' is not supported by Paddle-Lite. 

### ISSUE THREAD

**Issue by LMR2018** [marsplus-wjh/Picodet-PaddleLite-AndroidDemo#2]
pp-picodet模型转化为paddle-lite模型用于安卓部署时，paddle-lite版本是2.10rc，执行命令：paddle_lite_opt --model_dir=inference_model/picodet_s_320_coco --valid_targets=arm --optimize_out=picodet_s_320_coco_fp16 --enable_fp16=true出现这个错误Error: This model is not supported, because kernel for 'calib' is not supported by Paddle-Lite.

**Comment by marsplus-wjh** [comment]
建议在 paddle detecion repo：https://github.com/PaddlePaddle/PaddleDetection 提这个 issue 问一下作者哈，我当时 opt 构建的是 fp32 的模型。

**Comment by yatouxingren** [comment]
> 建议在 paddle detecion repo：https://github.com/PaddlePaddle/PaddleDetection 提这个 issue 问一下作者哈，我当时 opt 构建的是 fp32 的模型。

我也遇到了跟题主一样的问题： warning: the version of opt that transformed this model is not consistent with current Paddle-Lite version.
          version of opt:v2.10
          version of current Paddle-Lite:v2.9.1
2021-12-21 17:03:03.847 793-793/com.baidu.paddledetection.detection A/Paddle-Lite: [F 12/21 17: 3: 3.847 /island/Paddle-Lite/lite/core/program.cc RuntimeProgram:347] Check failed: (kernels.size() > 0): 0!>0 
    Error: This model is not supported, because kernel for 'calib' is not supported by Paddle-Lite.
2021-12-21 17:03:03.847 793-793/com.baidu.paddledetection.detection A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 793 (ction.detection), pid 793 (ction.detection)

 但我想问的一个问题是：
这里显示paddle lite版本为2.9.1 和 opt工具版本不一致，那么我要更换paddle lite版本到2.10 请问如何跟换啊，需要替换哪些文件？

**Comment by marsplus-wjh** [comment]
那个是 warning，不影响使用，我之前使用 opt 2.10 也会报这个警告。

**Comment by yatouxingren** [comment]
> 那个是 warning，不影响使用，我之前使用 opt 2.10 也会报这个警告。

嗯嗯 不过我修改了 因为我自己训练的model.nb 时用opt 2.10版本工具导出的，不改为2.10 会报其他错误
把app module下的build.gradle 中的https://paddlelite-demo.bj.bcebos.com/libs/android/paddle_lite_libs_v2_9_1.tar.gz 为 https://paddlelite-demo.bj.bcebos.com/libs/android/paddle_lite_libs_v2_10_rc.tar.gz 即可

**Comment by marsplus-wjh** [comment]
嗯嗯 也可以修改 lite 的版本解决

**Comment by LMR2018** [comment]
> 

@marsplus-wjh @yatouxingren    我把把app module下的build.gradle 中的https://paddlelite-demo.bj.bcebos.com/libs/android/paddle_lite_libs_v2_9_1.tar.gz 为 https://paddlelite-demo.bj.bcebos.com/libs/android/paddle_lite_libs_v2_10_rc.tar.gz 改了，也还是报这个错啊，太奇怪了，我是漏掉了什么吗？好像我把models里面的模型都删除了也还是报这个错误

**Comment by yatouxingren** [comment]
> > 
> 
> @marsplus-wjh @yatouxingren 我把把app module下的build.gradle 中的https://paddlelite-demo.bj.bcebos.com/libs/android/paddle_lite_libs_v2_9_1.tar.gz 为 https://paddlelite-demo.bj.bcebos.com/libs/android/paddle_lite_libs_v2_10_rc.tar.gz 改了，也还是报这个错啊，太奇怪了，我是漏掉了什么吗？好像我把models里面的模型都删除了也还是报这个错误

@LMR2018 你将logcat中打出的log，用 lite 或者  version of 关键字筛选下，确认下你的paddle lite版本号是多少，然后加一下log打印出来，加载的模型是不是你自己的模型
